name: still
favicon: null
layout_spectrum: 0.37392
typography_spectrum: 0.67516
title: still
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#9e9e9e'
    - '#6e6e6e'
    - '#363636'
    - '#0d0d0d'
  brandStrength: 0.25
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
